#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

console.log('🔧 Setting up environment variables for ACME Marketing');
console.log('');

// Check if .env already exists
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
  console.log('⚠️  .env file already exists. This will overwrite it.');
  console.log('');
}

console.log('📋 Please provide your Supabase credentials:');
console.log('   You can find these in your Supabase project dashboard:');
console.log('   https://supabase.com/dashboard/project/[YOUR-PROJECT-ID]/settings/api');
console.log('');

// Read from command line arguments or prompt
const args = process.argv.slice(2);
let supabaseUrl = args[0];
let supabaseKey = args[1];

if (!supabaseUrl) {
  console.log('❓ Enter your Supabase Project URL:');
  console.log('   (e.g., https://abcdefghijklmnop.supabase.co)');
  supabaseUrl = await readInput();
}

if (!supabaseKey) {
  console.log('❓ Enter your Supabase Anon/Public Key:');
  console.log('   (starts with "eyJ...")');
  supabaseKey = await readInput();
}

// Validate inputs
if (!supabaseUrl || !supabaseKey) {
  console.log('❌ Missing required credentials. Please try again.');
  process.exit(1);
}

if (!supabaseUrl.startsWith('https://')) {
  console.log('❌ Supabase URL should start with https://');
  process.exit(1);
}

if (!supabaseKey.startsWith('eyJ')) {
  console.log('❌ Supabase key should start with "eyJ"');
  process.exit(1);
}

// Create .env content
const envContent = `# Supabase Configuration
# Generated by setup-env.js
PUBLIC_SUPABASE_URL=${supabaseUrl}
PUBLIC_SUPABASE_ANON_KEY=${supabaseKey}

# Optional: SMTP Configuration for email sending
# These are used by the edge function for sending emails
SMTP_HOST=your_smtp_host_here
SMTP_PORT=587
SMTP_USER=your_smtp_username_here
SMTP_PASS=your_smtp_password_here
SMTP_FROM=noreply@acmemarketing.us
`;

// Write .env file
try {
  fs.writeFileSync(envPath, envContent);
  console.log('');
  console.log('✅ .env file created successfully!');
  console.log('');
  console.log('📝 Next steps:');
  console.log('   1. Restart your development server: npm run dev');
  console.log('   2. Test the API: node test-api.js');
  console.log('   3. Check the courses page: http://localhost:4322/courses');
  console.log('');
  console.log('🔒 Remember: .env is in .gitignore and will not be committed to git');
} catch (error) {
  console.log('❌ Error creating .env file:', error.message);
  process.exit(1);
}

// Helper function to read input (simplified for Node.js)
async function readInput() {
  return new Promise((resolve) => {
    process.stdin.once('data', (data) => {
      resolve(data.toString().trim());
    });
  });
} 